Repository movester/movester_client_product, pull requests merged in 2022-03, with the labels that each got.

#34 feature: 33: Join responsive UI
  src/components/UI/Auth/EmailAuth.js
  src/styles/FormWrapper.js
Labels: feature, UI/UX

#53 feat: error component
  package-lock.json
  package.json
  src/App.js
  src/components/molecules/Error.js
  src/components/molecules/Loading.js
  src/pages/Account.js
  src/pages/NotPound.js
Labels: feature

#49 feat: join feature connecting join API
  .eslintrc.json
  package.json
  src/components/UI/Auth/EmailAuth.js
  src/containers/Auth/JoinForm.js
  src/containers/Auth/LoginForm.js
  src/modules/auth.js
  src/modules/index.js
  src/modules/users.js
  src/services/authAPI.js
  src/services/defaultClient.js
  src/store/auth/authAsyncThunk.js
  src/store/auth/authSlice.js
  src/store/authSlice.js
  src/store/form/formSlice.js
  src/store/index.js
  src/store/user/userSlice.js
Labels: enhancement, feature

#52 Feature/50 login feature implementation
  src/components/UI/Auth/AuthForm.js
  src/components/UI/Auth/FindPassword.js
  src/components/common/Header.js
  src/components/elements/NavProfileButton.js
  src/components/molecules/ProfileDropMenu.js
  src/containers/Auth/LoginForm.js
  src/services/authAPI.js
  src/store/auth/authAsyncThunk.js
  src/store/auth/authSlice.js
Labels: enhancement, feature

#40 feat: record ruler implementation
  package-lock.json
  package.json
  src/components/Auth/AuthForm.js
  src/components/Auth/EditPassword.js
  src/components/Auth/EmailAuth.js
  src/components/Auth/FindPassword.js
  src/components/Auth/FindPasswordForm.js
  src/components/Auth/JoinForm.js
  src/components/Auth/LoginForm.js
  src/components/home/HomeComponent.js
  src/components/home/WeeklyCard.js
  src/components/record/Graph.js
  src/components/record/Ruler.js
  src/pages/EditPasswordPage.js
  src/pages/FindPasswordPage.js
  src/pages/Home.js
  src/pages/JoinPage.js
  src/pages/LoginPage.js
  src/pages/Record.js
  src/pages/Shoulder.js
  src/pages/WaistLeg.js
  src/services/defaultClient.js
  src/services/userAPI.js
  src/store/user/userAsyncThunk.js
  src/store/user/userSlice.js
Labels: feature, UI/UX
